apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aion-trading

resources:
  - namespace.yaml

commonLabels:
  app.kubernetes.io/part-of: aion-platform
  app.kubernetes.io/managed-by: kustomize
