"""ML stack validation report (Track A.4).

Compares the live-trading outcome distribution from ``trade_decisions``
across two windows — typically pre-hydration vs post-hydration of the
debate / sentiment / regime_hmm agents — and emits a markdown report
to ``docs/ML-VALIDATION-<DATE>.md``.

The brief's full scope also asks for a backtest replay (hydrated vs
hydrated=false) over a representative profile. That part is gated on
the backtesting service being up and a flag we don't yet have on the
service to disable hydration. This script focuses on the live-decision
half — the descriptive comparison the partner sees first — and the
report file calls out what's missing so a follow-up can complete it.

Usage:
    poetry run python scripts/ml_validation.py
    poetry run python scripts/ml_validation.py --pre-hours 48 --post-hours 24
    poetry run python scripts/ml_validation.py --output docs/ML-VALIDATION-2026-05-04.md
"""

from __future__ import annotations

import argparse
import asyncio
import collections
import json
import sys
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Dict, List, Optional

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from libs.config import settings  # noqa: E402
from libs.observability import get_logger  # noqa: E402
from libs.storage._timescale_client import TimescaleClient  # noqa: E402

logger = get_logger("scripts.ml_validation")


@dataclass
class WindowSummary:
    label: str
    start: datetime
    end: datetime
    total_decisions: int = 0
    outcome_counts: Dict[str, int] = field(default_factory=dict)
    avg_confidence: Optional[float] = None
    null_regime_rate: Optional[float] = None
    distinct_regimes: int = 0
    distinct_profiles: int = 0


async def _summarise_window(timescale: TimescaleClient, label: str, start: datetime, end: datetime) -> WindowSummary:
    summary = WindowSummary(label=label, start=start, end=end)

    rows = await timescale.fetch(
        """
        SELECT
            outcome,
            COUNT(*)                                          AS n,
            AVG((agents->>'final_confidence')::float)         AS avg_conf,
            COUNT(*) FILTER (WHERE regime IS NULL)            AS null_regime_rows,
            COUNT(DISTINCT (regime->>'regime'))               AS distinct_regimes,
            COUNT(DISTINCT profile_id)                        AS distinct_profiles
        FROM trade_decisions
        WHERE created_at BETWEEN $1 AND $2
        GROUP BY outcome
        ORDER BY outcome
        """,
        start,
        end,
    )
    total = 0
    confs: list[float] = []
    null_rows = 0
    regimes_seen = 0
    profiles_seen = 0
    for r in rows:
        outcome = r["outcome"]
        n = r["n"]
        summary.outcome_counts[outcome] = n
        total += n
        if r["avg_conf"] is not None:
            confs.append(float(r["avg_conf"]) * n)
        null_rows += r["null_regime_rows"] or 0
        regimes_seen = max(regimes_seen, r["distinct_regimes"] or 0)
        profiles_seen = max(profiles_seen, r["distinct_profiles"] or 0)

    summary.total_decisions = total
    summary.distinct_regimes = regimes_seen
    summary.distinct_profiles = profiles_seen
    if total:
        summary.avg_confidence = sum(confs) / total if confs else None
        summary.null_regime_rate = null_rows / total
    return summary


def _shifts(pre: WindowSummary, post: WindowSummary) -> List[Dict[str, object]]:
    rows: List[Dict[str, object]] = []
    keys = sorted(set(pre.outcome_counts) | set(post.outcome_counts))
    for k in keys:
        a = pre.outcome_counts.get(k, 0)
        b = post.outcome_counts.get(k, 0)
        a_pct = (a / pre.total_decisions) if pre.total_decisions else 0.0
        b_pct = (b / post.total_decisions) if post.total_decisions else 0.0
        rows.append({
            "outcome": k,
            "pre_count": a,
            "pre_pct": a_pct,
            "post_count": b,
            "post_pct": b_pct,
            "delta_pct": b_pct - a_pct,
        })
    return rows


def _format_md(pre: WindowSummary, post: WindowSummary) -> str:
    shift_rows = _shifts(pre, post)
    lines: list[str] = []
    lines.append(f"# ML Validation — {datetime.now(timezone.utc).date().isoformat()}")
    lines.append("")
    lines.append("> Auto-generated by `scripts/ml_validation.py` (Track A.4).")
    lines.append("> Compares decision outcome distributions across two windows.")
    lines.append("")
    lines.append("## Windows")
    lines.append("")
    lines.append(f"- **{pre.label}**: {pre.start.isoformat()} → {pre.end.isoformat()} — {pre.total_decisions} decisions")
    lines.append(f"- **{post.label}**: {post.start.isoformat()} → {post.end.isoformat()} — {post.total_decisions} decisions")
    lines.append("")
    if not pre.total_decisions or not post.total_decisions:
        lines.append("⚠️  One or both windows are empty. Outcome shift table omitted.")
        lines.append("")
    else:
        lines.append("## Outcome distribution shift")
        lines.append("")
        lines.append("| Outcome | Pre count | Pre % | Post count | Post % | Δ pp |")
        lines.append("|---------|----------:|------:|-----------:|-------:|------:|")
        for r in shift_rows:
            lines.append(
                f"| `{r['outcome']}` | {r['pre_count']} | {100*r['pre_pct']:.1f}% | {r['post_count']} | "
                f"{100*r['post_pct']:.1f}% | {100*r['delta_pct']:+.1f}pp |"
            )
        lines.append("")
    lines.append("## Diagnostics")
    lines.append("")
    lines.append("| Metric | Pre | Post |")
    lines.append("|--------|-----|------|")
    lines.append(
        f"| Avg final confidence | {pre.avg_confidence!r} | {post.avg_confidence!r} |"
    )
    lines.append(
        f"| Null-regime row rate | {pre.null_regime_rate!r} | {post.null_regime_rate!r} |"
    )
    lines.append(
        f"| Distinct regimes seen | {pre.distinct_regimes} | {post.distinct_regimes} |"
    )
    lines.append(
        f"| Distinct profiles active | {pre.distinct_profiles} | {post.distinct_profiles} |"
    )
    lines.append("")
    lines.append("## Interpretation")
    lines.append("")
    lines.append(_one_paragraph_interpretation(pre, post, shift_rows))
    lines.append("")
    lines.append("## What's missing from this report")
    lines.append("")
    lines.append(
        "- Backtest replay (hydrated vs hydrated=false) over a 14-day window. "
        "Requires a `--no-hydration` flag in `services/backtesting/` that doesn't "
        "yet exist; tracked separately."
    )
    lines.append(
        "- Statistical significance. Sample sizes are too small for robust "
        "frequentist tests; descriptive stats only."
    )
    lines.append("")
    return "\n".join(lines)


def _one_paragraph_interpretation(
    pre: WindowSummary,
    post: WindowSummary,
    shift_rows: List[Dict[str, object]],
) -> str:
    if not pre.total_decisions or not post.total_decisions:
        return (
            "Insufficient decisions in one or both windows to interpret. Wait until "
            "both windows accumulate at least 50 decisions and rerun."
        )

    biggest = max(shift_rows, key=lambda r: abs(r["delta_pct"]))
    direction = "increased" if biggest["delta_pct"] > 0 else "decreased"
    null_regime_change = (
        (post.null_regime_rate or 0.0) - (pre.null_regime_rate or 0.0)
        if pre.null_regime_rate is not None and post.null_regime_rate is not None
        else None
    )
    regime_note = ""
    if null_regime_change is not None:
        if null_regime_change < -0.1:
            regime_note = (
                f" The null-regime rate dropped by {abs(100*null_regime_change):.1f}pp, "
                "consistent with the HMM emitting real regimes — that's the change "
                "Track A.3 was meant to deliver."
            )
        elif null_regime_change > 0.05:
            regime_note = (
                " Null-regime rate increased post-hydration, which suggests either "
                "an HMM checkpoint regression or the pre window happened to be richer."
            )
    return (
        f"The largest distributional shift is `{biggest['outcome']}`, which "
        f"{direction} by {abs(100*biggest['delta_pct']):.1f}pp. "
        f"Average confidence moved from {pre.avg_confidence} to {post.avg_confidence}.{regime_note} "
        "If the gate-efficacy MVP (D.PR2) shows blocked-set would-be win rate "
        "exceeding passed-set realized win rate, the next move is PR3 — adaptive "
        "weights — to relax the over-blocking gate."
    )


async def _main(args: argparse.Namespace) -> int:
    timescale = TimescaleClient(settings.DATABASE_URL)
    await timescale.init_pool()
    try:
        now = datetime.now(timezone.utc)
        post_start = now - timedelta(hours=args.post_hours)
        pre_end = post_start
        pre_start = pre_end - timedelta(hours=args.pre_hours)

        pre = await _summarise_window(timescale, "pre-hydration", pre_start, pre_end)
        post = await _summarise_window(timescale, "post-hydration", post_start, now)
    finally:
        await timescale.close()

    output = Path(args.output) if args.output else (
        ROOT / "docs" / f"ML-VALIDATION-{now.date().isoformat()}.md"
    )
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(_format_md(pre, post))
    print(f"Wrote {output}")
    print(json.dumps({
        "pre_total": pre.total_decisions,
        "post_total": post.total_decisions,
        "pre_outcomes": pre.outcome_counts,
        "post_outcomes": post.outcome_counts,
    }, indent=2))
    return 0


def parse_args(argv: Optional[list] = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Pre/post ML hydration outcome comparison.")
    p.add_argument("--pre-hours", type=int, default=24)
    p.add_argument("--post-hours", type=int, default=24)
    p.add_argument("--output", default=None)
    return p.parse_args(argv)


if __name__ == "__main__":
    sys.exit(asyncio.run(_main(parse_args())))
