#!/usr/bin/env python3
"""Sync canonical agent skills into per-service prompt bundles.

Canonical skills live in ``prompts/skills/*.md`` (single source of truth).
``prompts/skills/manifest.json`` declares, per LLM-surface service, which
skills are bundled into that service's prompt assets at
``services/<service>/prompts/skills/<skill>.md``.

The copy is mechanical, idempotent, and deterministic: running the script
twice produces zero further changes. Bundled copies carry an AUTO-GENERATED
header and must never be edited by hand — ``scripts/ci/check_skill_drift.py``
fails when a bundle (or a registered inline copy) diverges from canonical.

Pattern source: ``anthropics/financial-services`` ``sync-agent-skills.py``
(TECH-DEBT-REGISTRY row 36).

Usage:
    python scripts/sync_agent_skills.py [--root PATH] [--dry-run]
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

SKILLS_SUBDIR = Path("prompts") / "skills"
MANIFEST_NAME = "manifest.json"
# Bundle location inside each service directory.
BUNDLE_SUBDIR = Path("prompts") / "skills"

HEADER_TEMPLATE = (
    "<!-- AUTO-GENERATED by scripts/sync_agent_skills.py -- DO NOT EDIT.\n"
    "     Canonical source: prompts/skills/{name}.md\n"
    "     Drift gate: scripts/ci/check_skill_drift.py -->\n"
)


def load_manifest(root: Path) -> dict:
    """Parse prompts/skills/manifest.json under ``root``."""
    manifest_path = root / SKILLS_SUBDIR / MANIFEST_NAME
    with open(manifest_path, "r", encoding="utf-8") as f:
        return json.load(f)


def read_canonical_skill(root: Path, name: str) -> str:
    """Canonical skill text, EOL-normalised to LF."""
    path = root / SKILLS_SUBDIR / f"{name}.md"
    return path.read_text(encoding="utf-8").replace("\r\n", "\n")


def render_bundle(name: str, canonical_text: str) -> str:
    """The exact bytes a synced bundle file must contain."""
    return HEADER_TEMPLATE.format(name=name) + canonical_text


def bundle_path(root: Path, service: str, skill: str) -> Path:
    return root / "services" / service / BUNDLE_SUBDIR / f"{skill}.md"


def sync(root: Path, dry_run: bool = False) -> list[Path]:
    """Write out-of-date bundles. Returns the paths created or changed.

    Deterministic (sorted iteration) and idempotent (an in-sync tree yields
    an empty list and zero writes).
    """
    manifest = load_manifest(root)
    changed: list[Path] = []
    for service in sorted(manifest.get("bundles", {})):
        for skill in sorted(manifest["bundles"][service]):
            expected = render_bundle(skill, read_canonical_skill(root, skill))
            target = bundle_path(root, service, skill)
            current = (
                target.read_text(encoding="utf-8").replace("\r\n", "\n")
                if target.exists()
                else None
            )
            if current != expected:
                changed.append(target)
                if not dry_run:
                    target.parent.mkdir(parents=True, exist_ok=True)
                    target.write_text(expected, encoding="utf-8", newline="\n")
    return changed


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="Repo root (default: inferred from this script's location).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Report what would change without writing.",
    )
    args = parser.parse_args(argv)

    changed = sync(args.root, dry_run=args.dry_run)
    verb = "would sync" if args.dry_run else "synced"
    if changed:
        for path in changed:
            print(f"{verb}: {path.relative_to(args.root).as_posix()}")
    print(f"sync_agent_skills: {len(changed)} bundle(s) {verb}; tree is in sync.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
