from decimal import Decimal

FAST_GATE_TIMEOUT_MS = 50
SENTIMENT_CACHE_TTL_S = 900
REDIS_ROLLING_WINDOW_SIZE = 1000

DEFAULT_CIRCUIT_BREAKER_PCT = Decimal('0.02')
DEFAULT_DRIFT_MULTIPLIER = Decimal('3.0')
DEFAULT_DRIFT_WINDOW_DAYS = 7
MIN_DRIFT_THRESHOLD_PCT = Decimal('0.15')

RSI_PERIOD = 14
MACD_FAST = 12
MACD_SLOW = 26
MACD_SIGNAL = 9

RECONCILIATION_DRIFT_THRESHOLD_PCT = Decimal('0.001')
HOT_DATA_RETENTION_DAYS = 7
COLD_BACKTEST_BOUNDARY_MONTHS = 12
THRESHOLD_PROXIMITY_BAND_PCT = Decimal('0.10')
