from enum import Enum, auto

class OrderSide(str, Enum):
    BUY = "BUY"
    SELL = "SELL"

class OrderStatus(str, Enum):
    PENDING = "PENDING"
    SUBMITTED = "SUBMITTED"
    CONFIRMED = "CONFIRMED"
    ROLLED_BACK = "ROLLED_BACK"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"

class EventType(str, Enum):
    MARKET_TICK = "MARKET_TICK"
    SIGNAL_GENERATED = "SIGNAL_GENERATED"
    SIGNAL_ABSTAINED = "SIGNAL_ABSTAINED"
    ORDER_APPROVED = "ORDER_APPROVED"
    ORDER_REJECTED = "ORDER_REJECTED"
    ORDER_EXECUTED = "ORDER_EXECUTED"
    ORDER_FAILED = "ORDER_FAILED"
    CIRCUIT_BREAKER_TRIGGERED = "CIRCUIT_BREAKER_TRIGGERED"
    BLACKLIST_BLOCKED = "BLACKLIST_BLOCKED"
    VALIDATION_PROCEED = "VALIDATION_PROCEED"
    VALIDATION_BLOCK = "VALIDATION_BLOCK"
    VALIDATION_TIMEOUT = "VALIDATION_TIMEOUT"
    REGIME_CHANGE = "REGIME_CHANGE"
    PNL_UPDATE = "PNL_UPDATE"
    ALERT_AMBER = "ALERT_AMBER"
    ALERT_RED = "ALERT_RED"
    SYSTEM_ALERT = "SYSTEM_ALERT"
    THRESHOLD_PROXIMITY = "THRESHOLD_PROXIMITY"

class Regime(str, Enum):
    TRENDING_UP = "TRENDING_UP"
    TRENDING_DOWN = "TRENDING_DOWN"
    RANGE_BOUND = "RANGE_BOUND"
    HIGH_VOLATILITY = "HIGH_VOLATILITY"
    CRISIS = "CRISIS"

class ValidationCheck(str, Enum):
    CHECK_1_STRATEGY = "CHECK_1_STRATEGY"
    CHECK_2_HALLUCINATION = "CHECK_2_HALLUCINATION"
    CHECK_3_BIAS = "CHECK_3_BIAS"
    CHECK_4_DRIFT = "CHECK_4_DRIFT"
    CHECK_5_ESCALATION = "CHECK_5_ESCALATION"
    CHECK_6_RISK_LEVEL = "CHECK_6_RISK_LEVEL"

class ValidationVerdict(str, Enum):
    GREEN = "GREEN"
    AMBER = "AMBER"
    RED = "RED"

class ValidationMode(str, Enum):
    FAST_GATE = "FAST_GATE"
    ASYNC_AUDIT = "ASYNC_AUDIT"

class SignalDirection(str, Enum):
    BUY = "BUY"
    SELL = "SELL"
    ABSTAIN = "ABSTAIN"

class PositionStatus(str, Enum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"
